spring:
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/pdv2cloud}
    username: ${DATABASE_USER:pdv2cloud}
    password: ${DATABASE_PASSWORD:pdv2cloud}
  flyway:
    clean-disabled: false

logging:
  level:
    com.pdv2cloud: DEBUG
