spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://postgres:5432/pdv2cloud}
    username: ${DATABASE_USER:pdv2cloud}
    password: ${DATABASE_PASSWORD:pdv2cloud}
  jpa:
    properties:
      hibernate:
        show_sql: false

logging:
  level:
    root: INFO

app:
  admin:
    email: ${ADMIN_EMAIL:admin@mercadoflow.com}
    password: ${ADMIN_PASSWORD:MercadoFlow@2026}
    name: ${ADMIN_NAME:Administrador}
