spring:
  datasource:
    url: ${DATABASE_URL:jdbc:sqlite:/data/pdv2cloud.db}
  jpa:
    properties:
      hibernate:
        show_sql: false
        type:
          preferred_uuid_jdbc_type: VARCHAR

logging:
  level:
    root: INFO
